### ISSUE TITLE
It keeps failing to work with vy.

### ISSUE THREAD

**Issue by iogf** [Yasushi/tern-chrome-extension#7]
I have developed an auto completion plugin for vy.

https://github.com/iogf/vy

i'm using .tern-config like.

{
  "libs": [
    "browser",
    "jquery", "ecma5"
  ],
  "loadEagerly": [
    "importantfile.js"
  ],
  "plugins": {
    "requirejs": {
      "baseURL": "./",
      "paths": {},
      "chrome-extension":{}
    },
    "node": {}
  }
}

it fails to give me completion for

chrome.

**Comment by Yasushi** [comment]
Please try demos/chrome.html 

I try completion in test.js(in tern-mode Emacs),  it was started to enter at least two characters.

**Comment by iogf** [comment]
well. i'm using vy, i would like to get it working with vy, do you access irc.freenode? i hang at #vy there. are you interested to give me support on getting it working with vy?

**Comment by Yasushi** [comment]
I wrote simple test client in python.
https://gist.github.com/Yasushi/bf50b6710dfab9fa3720dc5dd9d8b018 

```
node node_modules/tern/bin/tern --persistent --verbose --debug &
python3 tern_demo.py
```

**Comment by iogf** [comment]
i have runned tern as you said.
[tau@lambda ~]$ python3 ternchrometest.py
localhost:37303
200
{   'completions': [],
    'end': 28,
    'isObjectKey': False,
    'isProperty': True,
    'start': 25}
Traceback (most recent call last):
  File "ternchrometest.py", line 41, in <module>
    assert r['completions'] == [{'name': 'downloads', 'type': 'chrome.downloads'}]
AssertionError
[tau@lambda ~]$ 

the tern log

bash: cannot set terminal process group (1449): Inappropriate ioctl for device
bash: no job control in this shell
[tau@lambda ~]$ tern --persistent --verbose --debug 
Listening on port 37303
Request: {
  "query": {
    "type": "completions",
    "types": "true",
    "file": "test.js",
    "end": {
      "ch": 9,
      "line": 1
    },
    "docs": "true"
  },
  "files": [
    {
      "type": "full",
      "text": "/_global chrome_/\nchrome.dow\n",
      "name": "test.js"
    }
  ]
}
Response: {
  "start": 25,
  "end": 28,
  "isProperty": true,
  "isObjectKey": false,
  "completions": []
}

**Comment by Yasushi** [comment]
Add test case. works for me.
https://travis-ci.org/Yasushi/tern-chrome-extension/jobs/125368690

**Comment by Yasushi** [comment]
Why  "chrome-extension" in "requirejs" options?

```
  "plugins": {
    "requirejs": {
      "baseURL": "./",
      "paths": {},
      "chrome-extension": {}
    },
    "node": {}
  }
```

Works for me in follows.

```
  "plugins": {
    "requirejs": {
      "baseURL": "./",
      "paths": {}
    },
    "chrome-extension": {},
    "node": {}
  }
```
